### ISSUE TITLE
Drawing tiling patterns

### ISSUE THREAD

**Issue by roguh** [pablolessa/hturtle#2]
I'm not sure where is best to ask this question as I couldn't find a Questions section or contact info.

I'd wish to draw a tiling pattern, such as the hyperbolic heptagon tiles shown here:
https://polytope.miraheze.org/wiki/Heptagonal_tiling

Is this possible with `hturtle` as is? I'm aware other tools exist for drawing in hyperbolic space, but I like Python's Turtle graphics. I would appreciate any advice, especially as I'm not well versed in hyperbolic mathematics.

**Comment by pablolessa** [comment]
Hi Hugo,

You can draw these types of things with hturtle, but it's probably not the
best tool for this (I would go with dibujos hiperbolicos
<https://github.com/pablolessa/dibujos_hiperbolicos> using a triangle
group).

Here's some code (in the link you give the length of the side is wrong,
but using the second hyperbolic law of cosines
<https://en.wikipedia.org/wiki/Hyperbolic_law_of_cosines> on a triangle
with angles 2pi/7, pi/3, pi/3, I get the value r below).




*from hturtle import *r =
acosh((cos(2*pi/7)+cos(pi/3)**2)/sin(pi/3)**2)regularwalk(r,-60,7)allwalk(r,6,[-60,60],word=[])*

The second to last line should draw a single heptagon.  The last line tries
to draw all combinations of moving forward r and rotating 60 degrees.
This is very hacky (trying to go to depth 7 I get an error on my machine).



[image: hept.png]

**Comment by pablolessa** [comment]
PS:   I saw your pull request and it seems OK.  But I don't have time to
learn how to merge it or manage this type of requests in the future.  I
don't mind at all if you just fork the repo and put your own custom version
on github.  I wish someone would do this with this great java applet
<http://aleph0.clarku.edu/~djoyce/poincare/poincare.html> by David E. Joyce
(here's a link <http://www.plunk.org/~hatch/HyperbolicApplet/> that give a
.jar file, you run it with "java -jar HyperbolicApplet.jar").

**Comment by roguh** [comment]
Thanks, Pablo. I'll take a look at dibujos_hiperbolicos.

**Comment by roguh** [comment]
This is a very nice applet!

I'd be interested in using Python Turtle, though the mathematics behind it would be quite complicated. For an applet like the .jar you linked, I'd use a more efficient graphics tool.

Have you seen the game HyperRogue? It's a video game that takes place within hyperbolic space and efficiently draws quite a few types of tilings and other elements. Seems like a good way to build intuition for hyperbolic space.
